/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pab2022.frontend;

import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import pab2022.backend.Odpowiedz;
import pab2022.backend.Pytanie;
import pab2022.backend.Wyswietl;
/**
 *
 * @author Hubert
 */
public class PAB2022Interface extends javax.swing.JFrame {
    /**
     * Creates new form PAB2022Interface
     */
    public String odpowiedzUz;
    public int i;
    
    public PAB2022Interface() throws ClassNotFoundException {
        initComponents();
        Wyswietl s = new Wyswietl();
        pytania = s.wyswielPytania();
        odpowiedzi = s.dodajOdpowiedzi();
        wyswietl(0);
        odpowiedzi = s.dodajOdpowiedzi();
        
        btn1.addActionListener((java.awt.event.ActionEvent evt) -> {
            try {
                btn1ActionPerformed(evt);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
    }
    
    public void wyswietl(int i){
        Pytanie p = pytania.get(i);
        Odpowiedz o = odpowiedzi.get(i);
        PytanieArea.setText(o.getOdpowiedz());
        
        
    }
    
    
  

    public void btn1ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {     
        /*
        Wyswietl s = new Wyswietl();

        odpowiedzUz = odpText.getText();
        
        if(sprawdzOdp()==true){
            s.idPytania++;
            wyswietl();
        }
           
        else{
            JOptionPane.showMessageDialog(this,"Podano złą odpowiedź");
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
        */
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PytanieArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        odpText = new javax.swing.JTextArea();
        btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PytanieArea.setColumns(20);
        PytanieArea.setRows(5);
        jScrollPane1.setViewportView(PytanieArea);

        odpText.setColumns(20);
        odpText.setRows(5);
        jScrollPane2.setViewportView(odpText);

        btn1.setText("Sprawdź odpowiedź");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn1)
                        .addGap(129, 129, 129))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAB2022Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAB2022Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAB2022Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAB2022Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PAB2022Interface().setVisible(true);
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea PytanieArea;
    private javax.swing.JButton btn1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea odpText;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pytanie> pytania;
    private ArrayList<Odpowiedz> odpowiedzi;

}


