/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pab2022.frontend;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pab2022.backend.Odpowiedz;
import pab2022.backend.Pytanie;
import pab2022.backend.Wyswietl;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Hubert Jakub Szymon
 */
public class PAB2022Interface extends javax.swing.JFrame {
    /**
     * Creates new form PAB2022Interface
     */
    public String odpowiedzUz;
    public int i;
    

    
    public PAB2022Interface() throws ClassNotFoundException {
        
        initComponents();
        table_update();
        table_delete();
        Wyswietl s = new Wyswietl();
        pytania = s.wyswielPytania();
        odpowiedzi = s.dodajOdpowiedzi();
        wyswietl(0);
        
       
              
        btn1.addActionListener((java.awt.event.ActionEvent evt) -> {
            try {
                btn1ActionPerformed(evt);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
    }
    
    public void wyswietl(int i){
        Pytanie p = pytania.get(i);
        Odpowiedz o = odpowiedzi.get(i);
        PytanieArea.setText(p.getPytanie());

    }
    
    
  

    public void btn1ActionPerformed(java.awt.event.ActionEvent evt) throws ClassNotFoundException {     
        
        Wyswietl s = new Wyswietl();
        Odpowiedz o = odpowiedzi.get(i);
        
        odpowiedzUz = odpText.getText();
        
        if(odpowiedzUz.toUpperCase().equals(o.getOdpowiedz().toUpperCase())){
            try{
            wyswietl(++i);
            JOptionPane.showMessageDialog(this,"Dobra odpowiedź");
            odpText.setText("");
            }
            catch(java.lang.IndexOutOfBoundsException ex) {
                JOptionPane.showMessageDialog(this,"Wygrałeś!");
                this.dispose();
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Zła odpowiedź, przegrałeś!");
            this.dispose();
            System.out.println(o.getOdpowiedz());
 
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection con1;
    PreparedStatement insert;
    PreparedStatement insert2;

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PytanieArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        odpText = new javax.swing.JTextArea();
        btn1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dodPyt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        dodOdp = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablePyt = new javax.swing.JTable();
        button2 = new javax.swing.JButton();
        editPyt = new javax.swing.JTextField();
        editOdp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        delPyt = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Pytdel = new javax.swing.JLabel();
        delOdp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        PytanieArea.setEditable(false);
        PytanieArea.setColumns(20);
        PytanieArea.setRows(5);
        jScrollPane1.setViewportView(PytanieArea);

        odpText.setColumns(20);
        odpText.setRows(5);
        odpText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odpTextMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(odpText);

        btn1.setText("Sprawdź odpowiedź");

        jLabel7.setText("Podaj odpowiedz:");

        jLabel8.setText("Pytanie:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btn1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel8)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn1)
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("Gra", jPanel1);

        dodPyt.setColumns(20);
        dodPyt.setRows(5);
        jScrollPane3.setViewportView(dodPyt);

        jButton1.setText("Dodaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dodOdp.setColumns(20);
        dodOdp.setRows(5);
        jScrollPane4.setViewportView(dodOdp);

        jLabel1.setText("Wpisz pytanie:");

        jLabel2.setText("Wpisz odpowiedz:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(164, 164, 164))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dodaj pytanie", jPanel2);

        tablePyt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPyt", "Pytania", "idOdp", "Odpowiedzi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePyt.getTableHeader().setReorderingAllowed(false);
        tablePyt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePytMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablePyt);
        if (tablePyt.getColumnModel().getColumnCount() > 0) {
            tablePyt.getColumnModel().getColumn(0).setMinWidth(0);
            tablePyt.getColumnModel().getColumn(0).setMaxWidth(0);
            tablePyt.getColumnModel().getColumn(2).setMinWidth(0);
            tablePyt.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        button2.setText("Edytuj");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        editPyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPytActionPerformed(evt);
            }
        });

        editOdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOdpActionPerformed(evt);
            }
        });

        jLabel3.setText("Pytanie");

        jLabel4.setText("Odpowiedz");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(editPyt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editOdp, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addGap(196, 196, 196)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(button2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPyt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editOdp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edycja pytan", jPanel3);

        delPyt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPyt", "Pytanie", "idOdp", "Odpowiedzi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        delPyt.getTableHeader().setReorderingAllowed(false);
        delPyt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delPytMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(delPyt);
        if (delPyt.getColumnModel().getColumnCount() > 0) {
            delPyt.getColumnModel().getColumn(0).setMinWidth(0);
            delPyt.getColumnModel().getColumn(0).setMaxWidth(0);
            delPyt.getColumnModel().getColumn(2).setMinWidth(0);
            delPyt.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        jButton2.setText("Usun");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Pytanie:");

        jLabel6.setText("Odpowiedz:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pytdel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delOdp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pytdel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delOdp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Usuwanie pytan", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel Df = (DefaultTableModel)delPyt.getModel();
        int selectedIndex = delPyt.getSelectedRow();

        try {
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            int id2 = Integer.parseInt(Df.getValueAt(selectedIndex, 2).toString());

            int dialogResult = JOptionPane.showConfirmDialog(null,"Czy napewno chcesz usunac to pytanie?","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection polaczenie= DriverManager.getConnection
                ("jdbc:sqlserver://pab-server.database.windows.net:1433;database=PAB2022;user=pab2022@pab-server;password=zaq1@WSX;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");

                insert = polaczenie.prepareStatement("delete from Pytania where id=?");
                insert.setInt(1, id);
                insert.executeUpdate();

                insert2 = polaczenie.prepareStatement("delete from PrawOdp where id=?");
                insert2.setInt(1, id2);
                insert2.executeUpdate();

                JOptionPane.showMessageDialog(this,"Pytanie usunięte!");

                table_delete();
                table_update();
                editPyt.setText("");
                editOdp.setText("");
                Pytdel.setText("");
                delOdp.setText("");
                Pytdel.requestFocus();

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void delPytMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delPytMouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)delPyt.getModel();
        int selectedIndex = delPyt.getSelectedRow();

        Pytdel.setText(Df.getValueAt(selectedIndex,1).toString());
        delOdp.setText(Df.getValueAt(selectedIndex,3).toString());
    }//GEN-LAST:event_delPytMouseClicked

    private void editOdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editOdpActionPerformed

    private void editPytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPytActionPerformed

    }//GEN-LAST:event_editPytActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel Df = (DefaultTableModel)tablePyt.getModel();
        int selectedIndex = tablePyt.getSelectedRow();

        try {
            int id = Integer.parseInt(Df.getValueAt(selectedIndex, 0).toString());
            int id2 = Integer.parseInt(Df.getValueAt(selectedIndex, 2).toString());
            String pytanie = editPyt.getText();
            String odpowiedz = editOdp.getText();

            // załadowanie sterownika
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // utworzenie połączenia
            Connection polaczenie= DriverManager.getConnection
            ("jdbc:sqlserver://pab-server.database.windows.net:1433;database=PAB2022;user=pab2022@pab-server;password=zaq1@WSX;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");

            insert = polaczenie.prepareStatement("update Pytania set pytanie=? where id=?");
            insert.setString(1, pytanie);
            insert.setInt(2, id);
            insert.executeUpdate();
            insert2 = polaczenie.prepareStatement("update PrawOdp set odpowiedz=? where id=?");
            insert2.setString(1, odpowiedz);
            insert2.setInt(2, id2);
            insert2.executeUpdate();

            JOptionPane.showMessageDialog(this,"Edycja udana!");

            table_update();
            table_delete();

            editPyt.setText("");
            editOdp.setText("");
            editPyt.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void tablePytMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePytMouseClicked

        DefaultTableModel Df = (DefaultTableModel)tablePyt.getModel();
        int selectedIndex = tablePyt.getSelectedRow();

        editPyt.setText(Df.getValueAt(selectedIndex,1).toString());
        editOdp.setText(Df.getValueAt(selectedIndex,3).toString());
    }//GEN-LAST:event_tablePytMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pytanie = dodPyt.getText();
        String odpowiedz = dodOdp.getText();

        try {
            // załadowanie sterownika
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // utworzenie połączenia
            Connection polaczenie= DriverManager.getConnection
            ("jdbc:sqlserver://pab-server.database.windows.net:1433;database=PAB2022;user=pab2022@pab-server;password=zaq1@WSX;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");

            insert = polaczenie.prepareStatement("insert into Pytania(pytanie)values(?)");
            insert.setString(1, pytanie);
            insert.executeUpdate();
            insert2 = polaczenie.prepareStatement("insert into PrawOdp(odpowiedz)values(?)");
            insert2.setString(1, odpowiedz);
            insert2.executeUpdate();

            JOptionPane.showMessageDialog(this,"Pytanie dodane");

            table_update();
            table_delete();

            dodPyt.setText("");
            dodOdp.setText("");
            dodPyt.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void odpTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odpTextMouseClicked
        jTabbedPane1.setEnabled(false);

    }//GEN-LAST:event_odpTextMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        jTabbedPane1.setEnabledAt(0, false);
       
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PAB2022Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PAB2022Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PAB2022Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PAB2022Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PAB2022Interface().setVisible(true);
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private void table_update()
{
    int a;
  try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection polaczenie= DriverManager.getConnection
                            ("jdbc:sqlserver://pab-server.database.windows.net:1433;database=PAB2022;user=pab2022@pab-server;password=zaq1@WSX;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");
               
            insert = polaczenie.prepareStatement("select id,pytanie from Pytania ");
                ResultSet rs = insert.executeQuery();
                java.sql.ResultSetMetaData Rss = rs.getMetaData();
            insert2 = polaczenie.prepareStatement("select id,odpowiedz from PrawOdp");
                ResultSet rs2 = insert2.executeQuery();
                java.sql.ResultSetMetaData Rss2 = rs2.getMetaData();    
            a = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)tablePyt.getModel();
            Df.setRowCount(0);
            while (rs.next())
                {
                rs2.next();
                Vector v2 = new Vector();
              for(int i=1;i<=a;i++)
                {
                 v2.add(rs.getString("id"));
                 v2.add(rs.getString("pytanie"));
                 v2.add(rs2.getString("id"));
                 v2.add(rs2.getString("odpowiedz"));
                }
                Df.addRow(v2);
                }      
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
}  
      private void table_delete()
{
    int a;
  try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection polaczenie= DriverManager.getConnection
                            ("jdbc:sqlserver://pab-server.database.windows.net:1433;database=PAB2022;user=pab2022@pab-server;password=zaq1@WSX;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");
                      
            insert = polaczenie.prepareStatement("select id,pytanie from Pytania ");
                ResultSet rs = insert.executeQuery();
                java.sql.ResultSetMetaData Rss = rs.getMetaData();
            insert2 = polaczenie.prepareStatement("select id,odpowiedz from PrawOdp");
                ResultSet rs2 = insert2.executeQuery();
                java.sql.ResultSetMetaData Rss2 = rs2.getMetaData();
            a = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)delPyt.getModel();
            Df.setRowCount(0);

          while (rs.next())
            {
                rs2.next();
                Vector v2 = new Vector();
             for(int i=1;i<=a;i++)
             {
                v2.add(rs.getString("id"));
                v2.add(rs.getString("pytanie"));
                v2.add(rs2.getString("id"));
                v2.add(rs2.getString("odpowiedz"));
             }
             Df.addRow(v2);
            }            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PAB2022Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea PytanieArea;
    private javax.swing.JLabel Pytdel;
    private javax.swing.JButton btn1;
    private javax.swing.JButton button2;
    private javax.swing.JLabel delOdp;
    private javax.swing.JTable delPyt;
    private javax.swing.JTextArea dodOdp;
    private javax.swing.JTextArea dodPyt;
    private javax.swing.JTextField editOdp;
    private javax.swing.JTextField editPyt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea odpText;
    private javax.swing.JTable tablePyt;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pytanie> pytania;
    private ArrayList<Odpowiedz> odpowiedzi;

}


